server:
  port: 9015
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankapp_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
    hibernate:
      ddl-auto: update 
com:
  learning:
    jwtSecret: bankapplicationsecret
    jwtExpirationMs: 86400000